version: '3.1'

services:
  postgres:
    image: postgres:17  # or the version you want to use
    container_name: postgres-test-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: "books"  # Default database
    ports:
      - "5433:5432"  # Host port 5433 mapped to container's 5432
